<?php
return array(
    'multiform_action_form' => array(
        'id' => array('int', 11, 'null' => 0, 'autoincrement' => 1),
        'form_id' => array('int', 11, 'null' => 0),
        'action_code' => array('varchar', 50, 'null' => 0),
        'parent_id' => array('int', 11, 'default' => '0'),
        'sort' => array('int', 11, 'default' => '0'),
        'group_id' => array('int', 11, 'default' => '0'),
        'status' => array('tinyint', 1, 'null' => 0, 'default' => '0'),
        ':keys' => array(
            'PRIMARY' => 'id',
            'form_id' => 'form_id',
        ),
    ),
    'multiform_action_form_settings' => array(
        'form_id' => array('int', 11, 'null' => 0),
        'action_id' => array('int', 11, 'null' => 0),
        'param' => array('varchar', 255, 'null' => 0),
        'ext' => array('varchar', 255, 'null' => 0),
        'value' => array('text'),
        ':keys' => array(
            'action_id' => 'action_id',
        ),
    ),
    'multiform_action_group' => array(
        'id' => array('int', 11, 'null' => 0, 'autoincrement' => 1),
        'name' => array('varchar', 50, 'null' => 0),
        'form_id' => array('int', 11, 'null' => 0),
        'collapsed' => array('tinyint', 1, 'default' => '0'),
        'sort' => array('int', 11, 'default' => '-1'),
        ':keys' => array(
            'PRIMARY' => 'id',
            'form_id' => 'form_id',
        ),
    ),
    'multiform_condition' => array(
        'id' => array('int', 11, 'null' => 0, 'autoincrement' => 1),
        'form_id' => array('int', 11, 'null' => 0),
        'action' => array('varchar', 10, 'null' => 0),
        'target' => array('text', 'null' => 0),
        'andor' => array('tinyint', 1, 'null' => 0),
        'sort' => array('int', 11, 'null' => 0),
        'tab' => array('varchar', 20),
        'extra_tab' => array('varchar', 20),
        ':keys' => array(
            'PRIMARY' => 'id',
            'form_id' => 'form_id',
        ),
    ),
    'multiform_condition_params' => array(
        'condition_id' => array('int', 11, 'null' => 0),
        'source' => array('int', 11, 'null' => 0),
        'source_ext' => array('int', 11, 'null' => 0, 'default' => '0'),
        'operator' => array('varchar', 20, 'null' => 0),
        'value' => array('varchar', 255, 'null' => 0),
        ':keys' => array(
            'PRIMARY' => array('condition_id', 'source', 'source_ext', 'operator', 'value'),
            'condition_id' => 'condition_id',
        ),
    ),
    'multiform_field' => array(
        'id' => array('int', 11, 'null' => 0, 'autoincrement' => 1),
        'unique_id' => array('int', 11, 'null' => 0),
        'form_id' => array('int', 11, 'null' => 0, 'default' => '0'),
        'title' => array('varchar', 255, 'null' => 0, 'default' => ''),
        'title_pos' => array('varchar', 4, 'null' => 0, 'default' => ''),
        'type' => array('varchar', 50, 'null' => 0),
        'status' => array('tinyint', 1, 'null' => 0, 'default' => '1'),
        'code' => array('varchar', 50, 'null' => 0, 'default' => ''),
        'description' => array('text'),
        'class' => array('varchar', 50, 'null' => 0, 'default' => ''),
        'required' => array('tinyint', 1, 'null' => 0, 'default' => '0'),
        'disabled' => array('tinyint', 1, 'null' => 0, 'default' => '0'),
        'private' => array('tinyint', 1, 'null' => 0, 'default' => '0'),
        'hidden' => array('tinyint', 1, 'null' => 0, 'default' => '0'),
        'sort' => array('int', 11, 'null' => 0, 'default' => '0'),
        ':keys' => array(
            'PRIMARY' => 'id',
            'form_id' => 'form_id',
            'unique_id' => 'unique_id',
        ),
    ),
    'multiform_field_options' => array(
        'id' => array('int', 11, 'null' => 0, 'autoincrement' => 1),
        'field_id' => array('int', 11, 'null' => 0),
        'value' => array('varchar', 255, 'null' => 0),
        'image' => array('varchar', 30, 'null' => 0, 'default' => ''),
        'checked' => array('tinyint', 1, 'null' => 0, 'default' => '0'),
        'key' => array('varchar', 255, 'null' => 0, 'default' => ''),
        'ext' => array('varchar', 30, 'default' => ''),
        'formula' => array('varchar', 255, 'default' => ''),
        'sort' => array('int', 11, 'null' => 0),
        ':keys' => array(
            'PRIMARY' => 'id',
            'field_id' => 'field_id',
        ),
    ),
    'multiform_field_params' => array(
        'field_id' => array('int', 11, 'null' => 0),
        'param' => array('varchar', 50, 'null' => 0),
        'ext' => array('varchar', 50, 'null' => 0, 'default' => ''),
        'value' => array('text'),
        ':keys' => array(
            'PRIMARY' => array('field_id', 'param', 'ext'),
            'field_id' => 'field_id',
        ),
    ),
    'multiform_files' => array(
        'id' => array('int', 11, 'null' => 0, 'autoincrement' => 1),
        'record_id' => array('int', 11, 'null' => 0),
        'filename' => array('varchar', 255, 'null' => 0),
        'hash' => array('varchar', 20, 'null' => 0),
        ':keys' => array(
            'PRIMARY' => 'id',
            'hash' => array('hash', 'unique' => 1),
            'record_id' => 'record_id',
        ),
    ),
    'multiform_form' => array(
        'id' => array('int', 11, 'null' => 0, 'autoincrement' => 1),
        'url' => array('varchar', 20, 'null' => 0, 'default' => ''),
        'name' => array('varchar', 255, 'null' => 0, 'default' => ''),
        'title' => array('varchar', 255),
        'status' => array('tinyint', 1, 'null' => 0, 'default' => '1'),
        'description' => array('text'),
        'type' => array('tinyint', 1, 'null' => 0, 'default' => '1'),
        'start' => array('datetime'),
        'end' => array('datetime'),
        'create_datetime' => array('datetime'),
        'create_contact_id' => array('int', 11, 'default' => '0'),
        'hash' => array('varchar', 15),
        'meta_title' => array('varchar', 255, 'default' => ''),
        'meta_keywords' => array('text'),
        'meta_description' => array('text'),
        ':keys' => array(
            'PRIMARY' => 'id',
            'url' => 'url',
            'hash' => 'hash',
        ),
    ),
    'multiform_form_params' => array(
        'form_id' => array('int', 11, 'null' => 0),
        'param' => array('varchar', 255, 'null' => 0),
        'ext' => array('varchar', 255, 'null' => 0, 'default' => ''),
        'value' => array('text', 'null' => 0),
        ':keys' => array(
            'PRIMARY' => array('form_id', 'param'),
            'ext' => 'ext',
        ),
    ),
    'multiform_mask' => array(
        'id' => array('int', 11, 'null' => 0, 'autoincrement' => 1),
        'name' => array('varchar', 50, 'null' => 0),
        'mask' => array('varchar', 255, 'null' => 0),
        'error' => array('varchar', 255, 'null' => 0, 'default' => ''),
        ':keys' => array(
            'PRIMARY' => 'id',
        ),
    ),
    'multiform_record' => array(
        'id' => array('int', 11, 'null' => 0, 'autoincrement' => 1),
        'form_id' => array('int', 11, 'null' => 0),
        'create_datetime' => array('datetime', 'null' => 0),
        'create_contact_id' => array('int', 11, 'null' => 0, 'default' => '0'),
        'update_datetime' => array('datetime'),
        'update_contact_id' => array('int', 11, 'null' => 0, 'default' => '0'),
        'ip' => array('varchar', 15, 'null' => 0, 'default' => ''),
        'status' => array('tinyint', 1, 'null' => 0, 'default' => '0'),
        ':keys' => array(
            'PRIMARY' => 'id',
            'form_id' => 'form_id',
        ),
    ),
    'multiform_record_comment' => array(
        'id' => array('int', 11, 'null' => 0, 'autoincrement' => 1),
        'record_id' => array('int', 11, 'null' => 0),
        'name' => array('varchar', 50, 'default' => ''),
        'comment' => array('text'),
        'create_datetime' => array('datetime', 'null' => 0),
        'create_contact_id' => array('int', 11, 'null' => 0, 'default' => '0'),
        ':keys' => array(
            'PRIMARY' => 'id',
            'record_id' => 'record_id',
        ),
    ),
    'multiform_record_values' => array(
        'id' => array('int', 11, 'null' => 0, 'autoincrement' => 1),
        'record_id' => array('int', 11, 'null' => 0),
        'field_id' => array('int', 11, 'null' => 0),
        'cloned_index' => array('varchar', 50, 'null' => 0, 'default' => '0'),
        'ext' => array('varchar', 255, 'null' => 0),
        'value' => array('text', 'null' => 0),
        ':keys' => array(
            'PRIMARY' => 'id',
            'record_id' => array('record_id', 'field_id', 'cloned_index', 'ext', 'unique' => 1),
            'record' => 'record_id',
        ),
    ),
    'multiform_theme' => array(
        'id' => array('int', 11, 'null' => 0, 'autoincrement' => 1),
        'name' => array('varchar', 255, 'null' => 0),
        'create_datetime' => array('datetime', 'null' => 0),
        'create_contact_id' => array('int', 11, 'null' => 0, 'default' => '0'),
        'update_datetime' => array('datetime'),
        'update_contact_id' => array('int', 11, 'null' => 0, 'default' => '0'),
        'important' => array('tinyint', 1, 'default' => '0'),
        ':keys' => array(
            'PRIMARY' => 'id',
        ),
    ),
    'multiform_theme_settings' => array(
        'theme_id' => array('int', 11, 'null' => 0),
        'property' => array('varchar', 50, 'null' => 0),
        'field' => array('varchar', 50, 'null' => 0),
        'ext' => array('varchar', 50, 'null' => 0),
        'value' => array('varchar', 255),
        ':keys' => array(
            'PRIMARY' => array('theme_id', 'property', 'field', 'ext'),
        ),
    ),
);
