<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit8016c2cf65ddbc43ea3a9a84165f0ced
{
    public static $prefixLengthsPsr4 = array (
        'J' => 
        array (
            'JMathai\\PhpMultiCurl\\' => 21,
        ),
        'G' => 
        array (
            'Gettext\\Languages\\' => 18,
            'Gettext\\' => 8,
        ),
        'F' => 
        array (
            'Flintstone\\' => 11,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'JMathai\\PhpMultiCurl\\' => 
        array (
            0 => __DIR__ . '/..' . '/jmathai/php-multi-curl/src',
        ),
        'Gettext\\Languages\\' => 
        array (
            0 => __DIR__ . '/..' . '/gettext/languages/src',
        ),
        'Gettext\\' => 
        array (
            0 => __DIR__ . '/..' . '/gettext/gettext/src',
        ),
        'Flintstone\\' => 
        array (
            0 => __DIR__ . '/..' . '/fire015/flintstone/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit8016c2cf65ddbc43ea3a9a84165f0ced::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit8016c2cf65ddbc43ea3a9a84165f0ced::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit8016c2cf65ddbc43ea3a9a84165f0ced::$classMap;

        }, null, ClassLoader::class);
    }
}
